partial git pullpr

diff --git a/bin/git-submitpr b/bin/git-submitpr
--- a/bin/git-submitpr
+++ b/bin/git-submitpr
@@ -51,7 +51,7 @@ if [[ ! -d "$worktree_dir" ]]; then
 else
   # TODO: I've had the repo be in a bad state and maybe we need a cherry pick abort here, or on the cleanup instead
   if ! git -C "$worktree_dir" switch --quiet "$branch_name"; then
-    git branch -D "$branch_name"
+    echo "git branch -D" "$branch_name"
     exit 1
   fi
 fi
@@ -63,19 +63,20 @@ _detach_branch() {
 trap _detach_branch EXIT
 
 if ! git -C "$worktree_dir" cherry-pick "$commit" >/dev/null; then
+    echo "4"
   # TODO: if you ctrl-c out of the merge tool, it doesn't return false it exists the script only hitting the trap, so the cherry pick is not aborted
   if git -C "$worktree_dir" mergetool; then
     if ! git -C "$worktree_dir" -c core.editor=true cherry-pick --continue; then
       git -C "$worktree_dir" cherry-pick --abort || true
       _detach_branch
-      git branch -D "$branch_name"
+      echo "git branch -D " "$branch_name"
       echo "error: cherry picking failed, maybe there wasn't a commit to cherry pick?" >&2
       exit 1
     fi
   else
     git -C "$worktree_dir" cherry-pick --abort
     _detach_branch
-    git branch -D "$branch_name"
+    echo "git branch -D" "$branch_name"
     exit 1
   fi
 fi
@@ -98,19 +99,21 @@ cleanup_remote_branch() {
   echo "error: failed to create PR, deleting remote branch..." >&2
   git -C "$worktree_dir" push --quiet --delete origin "$branch_name" || true
   _detach_branch
-  git branch -D "$branch_name"
+  echo "git branch -D " "$branch_name"
   exit 1
 }
 
 error_file=$(mktemp)
 if git -C "$worktree_dir" remote get-url mine 2>/dev/null && git -C "$worktree_dir" push --quiet --set-upstream mine "$branch_name"; then
+  echo "1"
   # TODO: 'origin' might not be the only option
   origin_url=$(git -C "$worktree_dir" remote get-url origin)
   # TODO: does gh not support -C either?
   pushd "$worktree_dir" >/dev/null
-  gh pr create --web --repo "$origin_url" --base "$remote_branch_name" || cleanup_remote_branch
+#  gh pr create --web --repo "$origin_url" --base "$remote_branch_name" || cleanup_remote_branch
   popd >/dev/null
 elif git -C "$worktree_dir" push --quiet --set-upstream origin "$branch_name" 2> "$error_file"; then
+  echo "path 2"
   # TODO: does gh not support -C either?
   pushd "$worktree_dir" >/dev/null
   body_args=(--fill)
@@ -149,23 +152,24 @@ elif git -C "$worktree_dir" push --quiet --set-upstream origin "$branch_name" 2>
     esac
   done
 
-  if url=$(gh pr create "${body_args[@]}" --base "$remote_branch_name" "${pr_args[@]:---}" | grep github.com); then
-    # TODO: should I set subject and body?
-    if [[ -n "$merge_arg" ]] && ! gh pr merge "$url" --auto "$merge_arg"; then
-      native_open "$url"
-      echo "warning: failed to auto-merge PR with $merge_arg" >&2
-      exit 1
-    fi
-
-    native_open "$url"
-  else
-    cleanup_remote_branch
-  fi
+#  if url=$(gh pr create "${body_args[@]}" --base "$remote_branch_name" "${pr_args[@]:---}" | grep github.com); then
+#    # TODO: should I set subject and body?
+#    if [[ -n "$merge_arg" ]] && ! gh pr merge "$url" --auto "$merge_arg"; then
+#      native_open "$url"
+#      echo "warning: failed to auto-merge PR with $merge_arg" >&2
+#      exit 1
+#    fi
+#
+#    native_open "$url"
+#  else
+#    cleanup_remote_branch
+#  fi
 
   popd >/dev/null
 else
+  echo "3"
   echo "error: failed to create remote branch: $(cat "$error_file")" >&2
   _detach_branch
-  git branch -D "$branch_name"
+  echo "git branch -D " "$branch_name"
   exit 1
 fi
